[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[profile.celo]
src = "src-celo"
test = "test-celo"
out = "out-celo"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
0g_testnet = "${ZG_TESTNET_RPC}"
0g_mainnet = "${ZG_MAINNET_RPC}"
celo_mainnet = "https://forno.celo.org"

[etherscan]
0g_testnet = { key = "placeholder", url = "https://chainscan-galileo.0g.ai/open/api" }
0g_mainnet = { key = "placeholder", url = "https://chainscan.0g.ai/open/api" }
celo_mainnet = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
