// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title ZeroGentPayment
 * @notice Treasury contract for 0GENT x402 payments.
 *         Agents send native 0G tokens. Backend verifies via events.
 *         Each payment is tagged with a nonce to prevent replay.
 */
contract ZeroGentPayment is ReentrancyGuard {
    address public owner;
    uint256 public totalReceived;

    // nonce => true (prevents double-spend verification)
    mapping(bytes32 => bool) public usedNonces;

    event PaymentReceived(
        address indexed payer,
        uint256 amount,
        bytes32 indexed nonce,
        string resourceType,
        uint256 timestamp
    );

    event Withdrawn(address indexed to, uint256 amount);

    modifier onlyOwner() {
        require(msg.sender == owner, "ZGP: not owner");
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    /**
     * @notice Pay for a resource. Called by agents.
     * @param nonce Unique nonce (generated by backend, prevents replay)
     * @param resourceType Type of resource being paid for (e.g. "phone", "email")
     */
    function pay(bytes32 nonce, string calldata resourceType) external payable nonReentrant {
        require(msg.value > 0, "ZGP: zero payment");
        require(!usedNonces[nonce], "ZGP: nonce already used");

        usedNonces[nonce] = true;
        totalReceived += msg.value;

        emit PaymentReceived(msg.sender, msg.value, nonce, resourceType, block.timestamp);
    }

    /**
     * @notice Withdraw accumulated funds.
     */
    function withdraw(address payable to, uint256 amount) external onlyOwner {
        require(amount <= address(this).balance, "ZGP: insufficient balance");
        (bool ok, ) = to.call{value: amount}("");
        require(ok, "ZGP: transfer failed");
        emit Withdrawn(to, amount);
    }

    /**
     * @notice Check if a nonce has been used.
     */
    function isNonceUsed(bytes32 nonce) external view returns (bool) {
        return usedNonces[nonce];
    }

    receive() external payable {
        totalReceived += msg.value;
    }
}
